//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Api.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Northwind.Api.Common.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;TotalCount&quot;: 91,
        ///  &quot;TotalPages&quot;: 10,
        ///  &quot;CurrentPage&quot;: 1,
        ///  &quot;PageSize&quot;: 10,
        ///  &quot;Results&quot;: [
        ///    {
        ///      &quot;CustomerId&quot;: &quot;BSBEV&quot;,
        ///      &quot;CompanyName&quot;: &quot;B&apos;s Beverages&quot;,
        ///      &quot;Address&quot;: &quot;Fauntleroy Circus&quot;,
        ///      &quot;City&quot;: &quot;London&quot;,
        ///      &quot;PostalCode&quot;: &quot;EC2 5NT&quot;,
        ///      &quot;Country&quot;: &quot;UK&quot;,
        ///      &quot;Links&quot;: [
        ///        {
        ///          &quot;Rel&quot;: &quot;detail&quot;,
        ///          &quot;Href&quot;: &quot;http://localhost:6262/api/customers/BSBEV&quot;,
        ///          &quot;Title&quot;: &quot;Details&quot;
        ///        }
        ///      ]
        ///    },
        ///    {
        ///      &quot;CustomerId&quot;: &quot;CACTU&quot;,
        ///      &quot;CompanyName&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PagedCustomerJsonResponse {
            get {
                return ResourceManager.GetString("PagedCustomerJsonResponse", resourceCulture);
            }
        }
    }
}
